<a href="https://colab.research.google.com/github/ReuelNixon/learn-pytorch/blob/main/00_exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Exercises
All of the exercises are focused on practicing the code above.

You should be able to complete them by referencing each section or by following the resource(s) linked.

Resources:
1. Documentation reading - A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness). See the documentation on [torch.Tensor](https://pytorch.org/docs/stable/tensors.html#torch-tensor) and for [torch.cuda](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).
2. Create a random tensor with shape (7, 7).
3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).
4. Set the random seed to 0 and do exercises 2 & 3 over again.
5. Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one). If there is, set the GPU random seed to 1234.
6. Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed).
7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).
8. Find the maximum and minimum values of the output of 7.
9. Find the maximum and minimum index values of the output of 7.
10. Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

In [ ]:
import torch

In [ ]:
#2. Create a random tensor with shape (7, 7).
t1 = torch.rand(7,7)
t1

tensor([[0.9290, 0.2247, 0.0934, 0.8791, 0.9696, 0.1601, 0.1095],
        [0.9822, 0.1344, 0.6823, 0.4091, 0.6877, 0.2463, 0.5826],
        [0.0070, 0.2759, 0.9932, 0.2767, 0.1608, 0.2078, 0.6026],
        [0.3436, 0.2152, 0.8295, 0.5230, 0.7855, 0.2182, 0.3809],
        [0.9169, 0.0680, 0.5139, 0.8238, 0.6321, 0.9593, 0.1004],
        [0.7865, 0.6448, 0.8482, 0.5746, 0.4974, 0.2420, 0.2929],
        [0.7229, 0.4487, 0.8680, 0.2092, 0.3701, 0.3520, 0.4148]])

In [ ]:
#3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).
t2 = torch.rand(1,7)
t1 @ t2.T

tensor([[1.2666],
        [1.5735],
        [1.0558],
        [1.3021],
        [1.6232],
        [1.3973],
        [1.3564]])

In [ ]:
#4. Set the random seed to 0 and do exercises 2 & 3 over again.
torch.manual_seed(0)
t3 = torch.rand(7,7)
print(t3)

t4 = torch.rand(1,7)
print(t4)

t3 @ t4.T

tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]])
tensor([[0.4820, 0.8198, 0.9971, 0.6984, 0.5675, 0.8352, 0.2056]])


tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

In [ ]:
#5. set the GPU random seed to 1234.
torch.cuda.manual_seed(1234)
t5 = torch.rand(1,3, device='cuda')
torch.cuda.manual_seed(1234)
t6 = torch.rand(1,3, device='cuda')

print(t5)
print(t6)
print(t5 == t6)

tensor([[0.1272, 0.8167, 0.5440]], device='cuda:0')
tensor([[0.1272, 0.8167, 0.5440]], device='cuda:0')
tensor([[True, True, True]], device='cuda:0')


In [ ]:
#6. Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed).
torch.manual_seed(1234)
t7 = torch.rand(2,3, device='cuda')
torch.manual_seed(1234)
t8 = torch.rand(2,3, device='cuda')

print(t7)
print(t8)
print(t7 == t8)

tensor([[0.1272, 0.8167, 0.5440],
        [0.6601, 0.2721, 0.9737]], device='cuda:0')
tensor([[0.1272, 0.8167, 0.5440],
        [0.6601, 0.2721, 0.9737]], device='cuda:0')
tensor([[True, True, True],
        [True, True, True]], device='cuda:0')


In [ ]:
#7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).
t9 = t7 @ t8.T
t9

tensor([[0.9792, 0.8358],
        [0.8358, 1.4578]], device='cuda:0')

In [ ]:
#8. Find the maximum and minimum values of the output of 7.
t9.max(), t9.min()

(tensor(1.4578, device='cuda:0'), tensor(0.8358, device='cuda:0'))

In [ ]:
#9. Find the maximum and minimum index values of the output of 7.
t9.argmax(), t9.argmin()

(tensor(3, device='cuda:0'), tensor(1, device='cuda:0'))

In [ ]:
#10. Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.
torch.manual_seed(7)
t10 = torch.rand(1,1,1,10)
print(t10, '\t', t10.shape)
t10_squeezed = t10.squeeze()
print(t10_squeezed, '\t', t10_squeezed.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) 	 torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) 	 torch.Size([10])
