<a href="https://colab.research.google.com/github/ReuelNixon/learn-pytorch/blob/main/00_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Some basic tensor instantiation methods

In [ ]:
import torch

In [ ]:
t = torch.tensor([1,2,3])
t

tensor([1, 2, 3])

In [ ]:
MATRIX = torch.rand(3,3)
MATRIX

tensor([[0.4074, 0.5456, 0.7296],
        [0.5914, 0.5402, 0.5410],
        [0.4798, 0.7837, 0.8656]])

In [ ]:
torch.zeros(3,3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
torch.ones(3,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
torch.arange(start = 1, end = 10, step = 2)

tensor([1, 3, 5, 7, 9])

In [ ]:
torch.zeros_like(MATRIX)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
torch.ones_like(t)

tensor([1, 1, 1])

In [ ]:
t = torch.tensor([1,2,3],
                 dtype = torch.float16,
                 device = "cpu",
                 requires_grad = False)

### Getting information about the tensor

In [ ]:
print(t)
print(f"Datatype of tensor: {t.dtype}")
print(f"Dimension of tensor: {t.ndim}")
print(f"Shape of tensor: {t.shape}")
print(f"Device tensor is on: {t.device}")

tensor([1., 2., 3.], dtype=torch.float16)
Datatype of tensor: torch.float16
Dimension of tensor: 1
Shape of tensor: torch.Size([3])
Device tensor is on: cpu


`tensor.shape` is equivalent to `tensor.size()`

### Most frequent errors while dealing with tensors
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

### Tensor (Matrix) operations

#### Rules for elementwise operations on tensors
1. Same shape
2. Some datatype in some rare circumstances

#### Rules for performing matrix mutliplication (dot product)

1. The inner dimensions must match:
  - (3, 2) @ (3, 2) won't work
  - (2, 3) @ (3, 2) will work
  - (3, 2) @ (2, 3) will work

- The resulting matrix has the shape of the outer dimensions:
  - (2, 3) @ (3, 2) -> (2, 2)
  - (3, 2) @ (2, 3) -> (3, 3)

In [ ]:
t1 = torch.rand(3,3)
t2 = torch.rand(3,3)

t3 = torch.rand(4,4)

print(t1)
print(t2)
print(t3)

tensor([[0.6204, 0.8354, 0.6103],
        [0.1006, 0.3674, 0.2341],
        [0.1202, 0.7532, 0.3900]])
tensor([[0.9456, 0.3394, 0.8210],
        [0.3009, 0.6934, 0.4644],
        [0.4820, 0.8551, 0.8311]])
tensor([[0.5115, 0.6120, 0.0447, 0.5105],
        [0.4498, 0.5705, 0.1088, 0.5890],
        [0.8459, 0.2848, 0.4843, 0.5336],
        [0.2069, 0.7685, 0.7725, 0.8574]])


In [ ]:
t1 + 1

tensor([[1.6204, 1.8354, 1.6103],
        [1.1006, 1.3674, 1.2341],
        [1.1202, 1.7532, 1.3900]])

In [ ]:
t1 - 1

tensor([[-0.3796, -0.1646, -0.3897],
        [-0.8994, -0.6326, -0.7659],
        [-0.8798, -0.2468, -0.6100]])

In [ ]:
t1 * 2

tensor([[1.2407, 1.6708, 1.2206],
        [0.2011, 0.7348, 0.4682],
        [0.2403, 1.5064, 0.7800]])

In [ ]:
t1 / 2

tensor([[0.3102, 0.4177, 0.3051],
        [0.0503, 0.1837, 0.1171],
        [0.0601, 0.3766, 0.1950]])

In [ ]:
t1 + t2

tensor([[1.5659, 1.1748, 1.4312],
        [0.4014, 1.0607, 0.6985],
        [0.6021, 1.6083, 1.2211]])

In [ ]:
# Throws an error because of mismatching shape
# t1 + t3

RuntimeError: ignored

In [ ]:
t3 = torch.rand(2,3)
t4 = torch.rand(2,3)
print(t3)
print(t4)

tensor([[0.9035, 0.8699, 0.0256],
        [0.4976, 0.0011, 0.4428]])
tensor([[0.8672, 0.4999, 0.9967],
        [0.6473, 0.9440, 0.0995]])


In [ ]:
#Throws an error because of violating the rule for matrix multiplication
# t3 @ t4

RuntimeError: ignored

In [ ]:
t3.shape, t4.shape

(torch.Size([2, 3]), torch.Size([2, 3]))

To take the dot product of the two matrices we can transpose of either of the matrices

In [ ]:
t3 @ t4.T

tensor([[1.2439, 1.4086],
        [0.8735, 0.3672]])

### Finding the min, max, mean, sum, etc (tensor aggregation)

In [ ]:
t5 = torch.tensor([3,1,4,6,2,7,9,5,8])

In [ ]:
print(t5)
print(f"min of tensor: {t5.min()}")
print(f"max of tensor: {t5.max()}")
print(f"sum of tensor: {t5.sum()}")

tensor([3, 1, 4, 6, 2, 7, 9, 5, 8])
min of tensor: 1
max of tensor: 9
sum of tensor: 45


In [ ]:
# This will throw an error because mean can only be calculated for the tensors with float dtype
# print(f"mean of tensor: {t5.mean()}")

print(f"mean of tensor: {t5.type(torch.float32).mean()}")

RuntimeError: ignored

### Finding the positional min and max

In [ ]:
print(t5)
print(f"min of tensor is pesenst at the index: {t5.argmin()}")
print(f"max of tensor is pesenst at the index: {t5.argmax()}")

tensor([3, 1, 4, 6, 2, 7, 9, 5, 8])
min of tensor is pesenst at the index: 1
max of tensor is pesenst at the index: 6


### Reshaping, stacking, squeezing and unsqueezing tensors
- Reshaping - reshapes an input tensor to a defined shape
- View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
- Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
- Squeeze - removes all 1 dimensions from a tensor
- Unsqueeze - add a 1 dimension to a target tensor
- Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [ ]:
t6 = torch.arange(1.,10.)
print(t6, '\t' , t6.shape)

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]) 	 torch.Size([9])


In [ ]:
t6_reshaped = t6.reshape(1,9)
print(t6_reshaped, '\t' , t6_reshaped.shape)

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]) 	 torch.Size([1, 9])


In [ ]:
t6_reshaped = t6.reshape(3,3)
print(t6_reshaped, '\t' , t6_reshaped.shape)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]]) 	 torch.Size([3, 3])


In [ ]:
t6_view = t6.view(3,3)
print(t6_view, '\t' , t6_view.shape)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]]) 	 torch.Size([3, 3])


In [ ]:
# The difference between the reshape and view is that now if we change the t6_view, t6 also will get altered
t6_view[2][2] = 10
print(t6, '\t' , t6.shape)

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8., 10.]) 	 torch.Size([9])


In [ ]:
print(torch.stack((t6,t6,t6), dim = 0))  # similar to v-stack
print(torch.stack((t6,t6,t6), dim = 1))

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8., 10.],
        [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8., 10.],
        [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8., 10.]])
tensor([[ 1.,  1.,  1.],
        [ 2.,  2.,  2.],
        [ 3.,  3.,  3.],
        [ 4.,  4.,  4.],
        [ 5.,  5.,  5.],
        [ 6.,  6.,  6.],
        [ 7.,  7.,  7.],
        [ 8.,  8.,  8.],
        [10., 10., 10.]])


In [ ]:
print(torch.vstack((t6,t6,t6)))
print(torch.hstack((t6,t6,t6)))

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8., 10.],
        [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8., 10.],
        [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8., 10.]])
tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8., 10.,  1.,  2.,  3.,  4.,  5.,
         6.,  7.,  8., 10.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8., 10.])


In [ ]:
t6_unsqueezed = t6.unsqueeze(dim = 1)
t6_unsqueezed

tensor([[ 1.],
        [ 2.],
        [ 3.],
        [ 4.],
        [ 5.],
        [ 6.],
        [ 7.],
        [ 8.],
        [10.]])

In [ ]:
t6_unsqueezed.squeeze()

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8., 10.])

In [ ]:
t6_original = torch.rand(224, 224, 3)
t6_permuted = t6_original.permute(2,0,1)

print(f"Previous shape: {t6_original.shape}")
print(f"New shape: {t6_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


### Indexing (selecting data from tensors)

In [ ]:
t7 = torch.arange(1, 10).reshape(1, 3, 3)
t7, t7.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
print(t7[0])
print(t7[0][0])
print(t7[0][1][1])

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([1, 2, 3])
tensor(5)


In [ ]:
print(t7[:][:][0])
print(t7[:,:,0])

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([[1, 4, 7]])


### Numpy and PyTorch

In [ ]:
import numpy as np

In [ ]:
np_array = np.arange(1.0, 8.0)
t8 = torch.from_numpy(np_array)
np_array, t8

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

When converting from numpy -> pytorch, pytorch reflects numpy's default datatype of float64 unless specified otherwise


In [ ]:
t8 = torch.arange(1.,8.)
numpy_tensor = t8.numpy()
t8, numpy_tensor

(tensor([1., 2., 3., 4., 5., 6., 7.]),
 array([1., 2., 3., 4., 5., 6., 7.], dtype=float32))

### Reproducbility (trying to take random out of random)

In [ ]:
t9 = torch.rand(3, 4)
t10 = torch.rand(3, 4)

print(t9)
print(t10)
print(t9 == t10)

tensor([[0.1324, 0.4623, 0.1686, 0.6116],
        [0.1536, 0.8302, 0.3075, 0.3291],
        [0.1828, 0.8930, 0.7137, 0.5665]])
tensor([[0.4805, 0.8918, 0.2680, 0.2248],
        [0.9335, 0.8492, 0.2698, 0.6577],
        [0.7392, 0.5498, 0.4476, 0.0258]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
torch.manual_seed(42)
t9 = torch.rand(3, 4)
torch.manual_seed(42)
t10 = torch.rand(3, 4)

print(t9)
print(t10)
print(t9 == t10)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


### Running tensors and PyTorch objects on the GPUs

In [ ]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [ ]:
torch.cuda.device_count()

0

In [ ]:
t11 = torch.rand(9)
print(t11, t11.device)

tensor([0.8694, 0.5677, 0.7411, 0.4294, 0.8854, 0.5739, 0.2666, 0.6274, 0.2696]) cpu


In [ ]:
t_gpu = t11.to(device)
t_gpu

tensor([0.8694, 0.5677, 0.7411, 0.4294, 0.8854, 0.5739, 0.2666, 0.6274, 0.2696])

In [ ]:
# If tensor is on GPU, can't transform it to NumPy
# t_gpu.numpy()

In [ ]:
# To fix the GPU tensor with NumPy issue, we can first set it to the CPU
t_cpu = t_gpu.cpu().numpy()
t_cpu

array([0.86940444, 0.5677153 , 0.74109405, 0.4294045 , 0.8854429 ,
       0.57390445, 0.26658005, 0.62744915, 0.26963168], dtype=float32)